(ns slicer.gcode)

(def header-str
  "; generated by embodier 0.0.1")

(defn gcode 
  [cuts]
  (for [cut cuts]
    (let [z-str (str "G1 Z" (:cut-point cut) \newline)
          xy-str (for [line (:result cut)]
                   (if (vector? line)
                     (str "G1 X" (first line) " Y" (second line) \newline)
                     (str "G1 X" 
                          (first (first line)) " Y" (second (first line)) \newline " G1 X" 
                          (first (second line)) " Y" (second (second line)) \newline)))]
      (str z-str (apply str xy-str)))))
